// <auto-generated>
//     This code was generated by hand to mirror what ResXFileCodeGenerator
//     would emit but with the class made `public` so it can be referenced by
//     Remote UI XAML via clr-namespace bindings.
// </auto-generated>
using System.Globalization;
using System.Resources;

namespace PipelinesExplorer.VisualStudio.Resources;

/// <summary>
/// Strongly-typed accessor for <c>Strings.resx</c> and its localized variants.
/// Resolves automatically based on <see cref="CultureInfo.CurrentUICulture"/>;
/// Visual Studio sets the UI culture according to the IDE language pack
/// installed by the user.
/// </summary>
public static class Strings
{
    private static readonly ResourceManager _rm = new(
        "PipelinesExplorer.VisualStudio.Resources.Strings",
        typeof(Strings).Assembly);

    /// <summary>Underlying ResourceManager. Exposed so XAML can bind to it via x:Static if needed.</summary>
    public static ResourceManager ResourceManager => _rm;

    private static string Get(string key) => _rm.GetString(key, CultureInfo.CurrentUICulture) ?? key;

    // Toolbar
    public static string Toolbar_Refresh_Tooltip => Get(nameof(Toolbar_Refresh_Tooltip));
    public static string Toolbar_SwitchTenant_Tooltip => Get(nameof(Toolbar_SwitchTenant_Tooltip));
    public static string Toolbar_SignOut_Tooltip => Get(nameof(Toolbar_SignOut_Tooltip));

    // Welcome / signed-out panel
    public static string Welcome_SignInPrompt => Get(nameof(Welcome_SignInPrompt));
    public static string Welcome_SignInWithMicrosoft => Get(nameof(Welcome_SignInWithMicrosoft));
    public static string Welcome_PatHelp => Get(nameof(Welcome_PatHelp));
    public static string Welcome_SignInWithPat => Get(nameof(Welcome_SignInWithPat));
    public static string Welcome_PatField_Tooltip => Get(nameof(Welcome_PatField_Tooltip));

    // Connection header
    public static string Connection_MicrosoftEntra_Format => Get(nameof(Connection_MicrosoftEntra_Format));
    public static string Connection_DefaultTenant => Get(nameof(Connection_DefaultTenant));
    public static string Connection_Pat_Label => Get(nameof(Connection_Pat_Label));
    public static string Connection_Microsoft_Tooltip_Format => Get(nameof(Connection_Microsoft_Tooltip_Format));
    public static string Connection_Pat_Tooltip_Format => Get(nameof(Connection_Pat_Tooltip_Format));

    // Tree info nodes
    public static string Tree_Loading => Get(nameof(Tree_Loading));
    public static string Tree_NoOrganizations => Get(nameof(Tree_NoOrganizations));
    public static string Tree_NoOrganizations_Pat => Get(nameof(Tree_NoOrganizations_Pat));
    public static string Tree_NoProjects => Get(nameof(Tree_NoProjects));
    public static string Tree_NoPipelines => Get(nameof(Tree_NoPipelines));
    public static string Tree_NoTemplatesOrScripts => Get(nameof(Tree_NoTemplatesOrScripts));
    public static string Tree_UnknownRepository => Get(nameof(Tree_UnknownRepository));
    public static string Tree_UnknownSource => Get(nameof(Tree_UnknownSource));
    public static string Tree_InlineScript => Get(nameof(Tree_InlineScript));
    public static string Tree_Group_Templates => Get(nameof(Tree_Group_Templates));
    public static string Tree_Group_Scripts => Get(nameof(Tree_Group_Scripts));

    // Context menu
    public static string Context_Open => Get(nameof(Context_Open));
    public static string Context_LinkWorkspace => Get(nameof(Context_LinkWorkspace));
    public static string Context_UnlinkWorkspace => Get(nameof(Context_UnlinkWorkspace));
    public static string Context_SelectBranch => Get(nameof(Context_SelectBranch));

    // Tenant picker
    public static string TenantPicker_Title => Get(nameof(TenantPicker_Title));
    public static string TenantPicker_Prompt => Get(nameof(TenantPicker_Prompt));
    public static string TenantPicker_DefaultSubtitle => Get(nameof(TenantPicker_DefaultSubtitle));
    public static string TenantPicker_NoTenants => Get(nameof(TenantPicker_NoTenants));

    // Branch picker
    public static string BranchPicker_NoBranches => Get(nameof(BranchPicker_NoBranches));
    public static string BranchPicker_Prompt_Format => Get(nameof(BranchPicker_Prompt_Format));
    public static string BranchPicker_Failed_Format => Get(nameof(BranchPicker_Failed_Format));
    public static string BranchPicker_UseDefault => Get(nameof(BranchPicker_UseDefault));
    public static string BranchPicker_Title => Get(nameof(BranchPicker_Title));

    // Reset
    public static string Reset_Confirm => Get(nameof(Reset_Confirm));
    public static string Reset_Failed_Format => Get(nameof(Reset_Failed_Format));

    // Generic
    public static string MicrosoftSignIn_Failed_Format => Get(nameof(MicrosoftSignIn_Failed_Format));
    public static string ShowLogs_Failed_Format => Get(nameof(ShowLogs_Failed_Format));
    public static string SelectTenant_Prompt => Get(nameof(SelectTenant_Prompt));
    public static string SelectTenant_Failed_Format => Get(nameof(SelectTenant_Failed_Format));
    public static string OpenItem_OpenFailed_Format => Get(nameof(OpenItem_OpenFailed_Format));
    public static string OpenItem_FileNotFoundOnBranch_Format => Get(nameof(OpenItem_FileNotFoundOnBranch_Format));
    public static string OpenItem_FileNotFoundDefault_Format => Get(nameof(OpenItem_FileNotFoundDefault_Format));
    public static string OpenItem_RelinkWorkspace => Get(nameof(OpenItem_RelinkWorkspace));
    public static string OpenItem_OpenInBrowser => Get(nameof(OpenItem_OpenInBrowser));
    public static string OpenItem_PickFolder_Title_Format => Get(nameof(OpenItem_PickFolder_Title_Format));

    // Accessibility
    public static string A11y_Tree_Name => Get(nameof(A11y_Tree_Name));
    public static string A11y_PatField_Name => Get(nameof(A11y_PatField_Name));
    public static string A11y_TenantPicker_ComboBox_Name => Get(nameof(A11y_TenantPicker_ComboBox_Name));
    public static string A11y_BranchPicker_ComboBox_Name => Get(nameof(A11y_BranchPicker_ComboBox_Name));
    public static string A11y_Filter_Name => Get(nameof(A11y_Filter_Name));

    // Filter (Plan 001)
    public static string Filter_Placeholder => Get(nameof(Filter_Placeholder));
    public static string Filter_Clear_Tooltip => Get(nameof(Filter_Clear_Tooltip));
    public static string Filter_LoadedScope_Tooltip => Get(nameof(Filter_LoadedScope_Tooltip));
    public static string Filter_Status_Scanning_Format => Get(nameof(Filter_Status_Scanning_Format));
    public static string Filter_Status_NoResults_Format => Get(nameof(Filter_Status_NoResults_Format));
    public static string Filter_Status_Ready_Format => Get(nameof(Filter_Status_Ready_Format));
    public static string Filter_Status_Capped_Format => Get(nameof(Filter_Status_Capped_Format));

    // Link workspace -> auto-detected branch prompt (post-link offer)
    public static string LinkWorkspace_DetectedBranch_Format => Get(nameof(LinkWorkspace_DetectedBranch_Format));
    public static string LinkWorkspace_UseThisBranch => Get(nameof(LinkWorkspace_UseThisBranch));
    public static string LinkWorkspace_KeepDefaultBranch => Get(nameof(LinkWorkspace_KeepDefaultBranch));

    // Unauthorized (401/403) recovery prompt
    public static string Unauthorized_Message_Format => Get(nameof(Unauthorized_Message_Format));
    public static string Unauthorized_SignInMicrosoft => Get(nameof(Unauthorized_SignInMicrosoft));
    public static string Unauthorized_SignInPat => Get(nameof(Unauthorized_SignInPat));

    // Add-organization panel (Plan 002 phase D)
    public static string AddOrg_Header => Get(nameof(AddOrg_Header));
    public static string AddOrg_RequiresPatSignIn => Get(nameof(AddOrg_RequiresPatSignIn));
    public static string AddOrg_DeprecationNotice => Get(nameof(AddOrg_DeprecationNotice));
    public static string AddOrg_OrgLabel => Get(nameof(AddOrg_OrgLabel));
    public static string AddOrg_OrgHint => Get(nameof(AddOrg_OrgHint));
    public static string AddOrg_OrgFieldHelp => Get(nameof(AddOrg_OrgFieldHelp));
    public static string AddOrg_PatLabel => Get(nameof(AddOrg_PatLabel));
    public static string AddOrg_PatFieldHelp => Get(nameof(AddOrg_PatFieldHelp));
    public static string AddOrg_HistoryLabel => Get(nameof(AddOrg_HistoryLabel));
    public static string AddOrg_Verify => Get(nameof(AddOrg_Verify));
    public static string AddOrg_Cancel => Get(nameof(AddOrg_Cancel));
    public static string AddOrg_OrgRequired => Get(nameof(AddOrg_OrgRequired));
    public static string AddOrg_PatRequired => Get(nameof(AddOrg_PatRequired));
    public static string AddOrg_Error_Unauthorized_Format => Get(nameof(AddOrg_Error_Unauthorized_Format));
    public static string AddOrg_Error_NotFound_Format => Get(nameof(AddOrg_Error_NotFound_Format));
    public static string AddOrg_Error_Network_Format => Get(nameof(AddOrg_Error_Network_Format));
}
